zookeepers="vm1 vm2"
nodes="vm1 vm2"
domains="nar.blockr car.blockr"
orderer_names="NAR-Orderer-0 CAR-Orderer-0"
orderers="Orderer1MSP Orderer2MSP"
peer_names="NAR-Peer-0 CAR-Peer-0"
peers="Org1MSP Org2MSP"
